### ISSUE TITLE
Is this project dead as the REST version of it is?

### ISSUE THREAD

**Issue by zark0-UwU** [ChrisMichaelPerezSantiago/animeflv-gql#1]
Hi, I am working on a discord bot for a class project, where I need to access the Information on https://www3.animeflv.net/ but i'd prefer to use an proper api rather than an scraper api or scraping it myself.

Not shure if this is also an scraper, but definetely looks the best (in terms of documentation). But ii couldn't help myself to notice that the rest version of this api has a goodbye nessage, saying that the project is dead, I would like to know if this is also dead for the same reason, or any information really abut the project

**Comment by chrismichaelps** [comment]
@zark0-UwU  Hello,

It's been a long time since I've maintained the API. 🥲

In any case, you can look at the library that had also been implemented, but it has been out of maintenance for a long time. 😫

Repository:
https://github.com/ChrisMichaelPerezSantiago/animeflv

Here you will find the functions and how they were implemented.
https://github.com/ChrisMichaelPerezSantiago/animeflv/blob/master/src/api/api.js

**Comment by zark0-UwU** [comment]
HI! thanks for your response.
I just noticed you use web scraping, it is not what i was looking for, but your implemaentation looks good so far.
If I use any of theese two, it most likely be the rest one, to reduce layers, and if i do so, I may improve on it on a fork of mine.
